#!/bin/sh

/usr/bin/invoke_app "$@" -C @tool/bin/CellSortHexCC3D.sh -t cellsorthexcc3d \
                         -u compucell3d-4.4.0 \
                         -w captive \
                         -r none
